import type { Activity, CalendarEvent, Course, FileItem, Note, Task } from './types';

export const seedCourses: Course[] = [
  {
    id: 'course-1',
    name: 'Statistika II',
    code: 'STAT-205',
    lecturer: 'Dr. Nadia Putri',
    tone: 'coral',
    progress: 68,
    tasks: 2,
    files: 12,
    schedule: 'Selasa 08.00–10.30',
    room: 'Gedung B · Ruang 204',
  },
  {
    id: 'course-2',
    name: 'Manajemen Operasi',
    code: 'MGT-214',
    lecturer: 'Rizky Pratama, M.M.',
    tone: 'amber',
    progress: 54,
    tasks: 1,
    files: 8,
    schedule: 'Selasa 13.30–16.00',
    room: 'Online · Google Meet',
  },
  {
    id: 'course-3',
    name: 'Pemrograman Web',
    code: 'IF-220',
    lecturer: 'Andi Wijaya, M.Kom.',
    tone: 'blue',
    progress: 76,
    tasks: 1,
    files: 16,
    schedule: 'Senin 10.00–12.30',
    room: 'Lab Komputer A',
  },
  {
    id: 'course-4',
    name: 'Metode Penelitian',
    code: 'MET-201',
    lecturer: 'Dr. Sari Wulandari',
    tone: 'purple',
    progress: 41,
    tasks: 1,
    files: 6,
    schedule: 'Kamis 13.00–15.30',
    room: 'Gedung C · Ruang 101',
  },
];

export const seedTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Selesaikan analisis regresi',
    description: 'Gunakan dataset penjualan untuk menghitung koefisien regresi berganda. Sertakan interpretasi hasil.',
    course: 'Statistika II',
    due: 'Hari ini, 21.00',
    dueDate: '2026-09-08',
    priority: 'high',
    status: 'in_progress',
  },
  {
    id: 'task-2',
    title: 'Baca studi kasus rantai pasok',
    description: 'Bab 7 halaman 142–168. Buat ringkasan poin utama.',
    course: 'Manajemen Operasi',
    due: 'Besok, 10.00',
    dueDate: '2026-09-09',
    priority: 'medium',
    status: 'todo',
  },
  {
    id: 'task-3',
    title: 'Rapikan catatan pertemuan 5',
    course: 'Pemrograman Web',
    due: 'Jum, 12 Sep',
    dueDate: '2026-09-12',
    priority: 'low',
    status: 'todo',
  },
  {
    id: 'task-4',
    title: 'Kirim revisi proposal kelompok',
    description: 'Tambahkan metodologi penelitian bagian 3.2 sesuai feedback dosen.',
    course: 'Metode Penelitian',
    due: 'Sen, 15 Sep',
    dueDate: '2026-09-15',
    priority: 'high',
    status: 'todo',
  },
];

export const seedNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Regresi Linear Berganda',
    course: 'Statistika II',
    body: 'Model regresi digunakan untuk melihat hubungan antara satu variabel dependen dan beberapa variabel independen.\n\nAsumsi penting:\n• Linearitas\n• Independensi residual\n• Homoskedastisitas\n• Normalitas residual\n\nRumus: Y = β₀ + β₁X₁ + β₂X₂ + ε',
    updated: '20 menit lalu',
  },
  {
    id: 'note-2',
    title: 'Rangkuman supply chain',
    course: 'Manajemen Operasi',
    body: 'Fokus pertemuan: aliran material, informasi, dan uang dari pemasok hingga konsumen.\n\nKonsep kunci:\n- Just-in-time\n- Bullwhip effect\n- Vendor managed inventory',
    updated: 'Kemarin',
  },
  {
    id: 'note-3',
    title: 'React server components',
    course: 'Pemrograman Web',
    body: 'Catatan tentang batas server/client component dan strategi data fetching.\n\nServer component: tidak bisa useState/useEffect\nClient component: butuh "use client" directive',
    updated: '2 hari lalu',
  },
];

export const seedFiles: FileItem[] = [
  {
    id: 'file-1',
    name: 'Modul Regresi.pdf',
    type: 'PDF',
    size: '3,8 MB',
    course: 'Statistika II',
    updated: '20 menit lalu',
    starred: true,
  },
  {
    id: 'file-2',
    name: 'Data Penjualan.xlsx',
    type: 'XLSX',
    size: '428 KB',
    course: 'Statistika II',
    updated: 'Kemarin',
  },
  {
    id: 'file-3',
    name: 'Supply Chain Week 5.pptx',
    type: 'PPTX',
    size: '8,1 MB',
    course: 'Manajemen Operasi',
    updated: '2 hari lalu',
  },
  {
    id: 'file-4',
    name: 'Proposal Penelitian.docx',
    type: 'DOCX',
    size: '1,2 MB',
    course: 'Metode Penelitian',
    updated: '4 hari lalu',
    shared: true,
  },
  {
    id: 'file-5',
    name: 'Tutorial React Hooks.pdf',
    type: 'PDF',
    size: '2,4 MB',
    course: 'Pemrograman Web',
    updated: '5 hari lalu',
  },
];

export const seedActivities: Activity[] = [
  {
    id: 'act-1',
    actor: 'Kamu',
    action: 'menyelesaikan task',
    resource: 'Kuis regresi dasar',
    time: 'Hari ini, 10.42',
    status: 'success',
    authorization: 'User action',
  },
  {
    id: 'act-2',
    actor: 'Gemini',
    action: 'merangkum file',
    resource: 'Modul Regresi.pdf',
    time: 'Hari ini, 09.18',
    status: 'success',
    authorization: 'Allow once',
  },
  {
    id: 'act-3',
    actor: 'Google Calendar',
    action: 'menyinkronkan event',
    resource: 'Manajemen Operasi',
    time: 'Kemarin, 17.06',
    status: 'success',
    authorization: 'OAuth scope',
  },
  {
    id: 'act-4',
    actor: 'Gemini',
    action: 'memindahkan 3 file',
    resource: 'Statistika II / Materi',
    time: 'Kemarin, 14.30',
    status: 'success',
    authorization: 'Allow once',
  },
];

export const seedCalendarEvents: CalendarEvent[] = [
  {
    id: 'evt-1',
    title: 'Statistika II',
    date: '2026-09-08',
    startTime: '08:00',
    endTime: '10:30',
    course: 'Statistika II',
    type: 'class',
    color: 'coral',
  },
  {
    id: 'evt-2',
    title: 'Deadline analisis regresi',
    date: '2026-09-08',
    course: 'Statistika II',
    type: 'deadline',
    color: 'coral',
  },
  {
    id: 'evt-3',
    title: 'Manajemen Operasi',
    date: '2026-09-08',
    startTime: '13:30',
    endTime: '16:00',
    course: 'Manajemen Operasi',
    type: 'class',
    color: 'amber',
  },
  {
    id: 'evt-4',
    title: 'Pemrograman Web',
    date: '2026-09-15',
    startTime: '10:00',
    endTime: '12:30',
    course: 'Pemrograman Web',
    type: 'class',
    color: 'blue',
  },
  {
    id: 'evt-5',
    title: 'Metode Penelitian',
    date: '2026-09-10',
    startTime: '13:00',
    endTime: '15:30',
    course: 'Metode Penelitian',
    type: 'class',
    color: 'purple',
  },
  {
    id: 'evt-6',
    title: 'Kirim revisi proposal',
    date: '2026-09-15',
    course: 'Metode Penelitian',
    type: 'deadline',
    color: 'purple',
  },
];
